### ISSUE TITLE
Room - Invite friends

### ISSUE THREAD

**Issue by zyhou** [Euregan/oeaki#7]
Invite friends room

## Problem

How to invite friends in my game?

## Proposal

- share link

![image](https://user-images.githubusercontent.com/2212144/79225506-18b82100-7e5d-11ea-92f6-7be8df40b603.png)

**Comment by HALLERPierre** [comment]
I think this should be our priority and a shareable link seems a good idea. 
As I see it, when a user is on a room page (identified by an uuid maybe ?), he should be added to a "socket room" serve side so the WebRTC negotiation can be done.

Maybe we should add a chat in this page ? It will allow us to test easily the webrtc connection and it's nice for users to be able to chat before the game ?
